// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJkg7dLBHxHwh1jnj9Dup8KdU4A8L-XPo',
    appId: '1:534616756946:android:4accf6ffc7f72fd5f7130b',
    messagingSenderId: '534616756946',
    projectId: 'ai-interview-simulator-a8230',
    storageBucket: 'ai-interview-simulator-a8230.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD0iQqpajwOnwKF1DiT69HV40RT5sCpI8',
    appId: '1:534616756946:web:f9f4b67aefaab291f7130b',
    messagingSenderId: '534616756946',
    projectId: 'ai-interview-simulator-a8230',
    authDomain: 'ai-interview-simulator-a8230.firebaseapp.com',
    storageBucket: 'ai-interview-simulator-a8230.firebasestorage.app',
    measurementId: 'G-6M8FYGBWBX',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD0iQqpajwOnwKF1DiT69HV40RT5sCpI8',
    appId: '1:534616756946:web:7073bfe85a5e7f7ff7130b',
    messagingSenderId: '534616756946',
    projectId: 'ai-interview-simulator-a8230',
    authDomain: 'ai-interview-simulator-a8230.firebaseapp.com',
    storageBucket: 'ai-interview-simulator-a8230.firebasestorage.app',
    measurementId: 'G-QGP07JYCF9',
  );

}